spring.application.name=email

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=flavienrandria81@gmail.com
spring.mail.password=bfejhcwdfrubnuzu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=8073
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG
logging.level.jakarta.mail=DEBUG